### ISSUE TITLE
Add support for anonymous users

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#16] opened 2020-07-11 16:06 UTC
We should permit anonymous users to share datasets.

Case 1:
=====

Anonymous sharing.

`ddb share *.JPG` 

 * Tag of dataset is `_/randomUUID` (where `_` is a special, reserved organization name)
 * There should be options in the server configuration to: a) Set time limits after which anonymous datasets are removed (e.g. remove all anonymous datasets if not claimed after 24 hours) b) Set size (MB of data) limits for anonymous datasets.

Case 2:
=====

Logged-in sharing.

`ddb login`
`ddb share dir/`

 * Tag of dataset is `<username>/randomUUID`
 * There should be limit checks as well at some point, but we don't have to implement them right away.

Case 3:
=====

Logged-in sharing with user-specified tag.

`ddb login`
`ddb share *.JPG --tag mydataset`

 * Tag of dataset is `<username>/mydataset`

`ddb login`
`ddb share *.JPG --tag orgname/mydataset`

 * Tag of dataset is `orgname/mydataset`
 * System needs to verify that the logged-in user has permissions to write to orgname.

**Comment by HeDo88TH** [comment] 2020-09-29 23:03
Duplicate of #32

**Closed by HeDo88TH** 2020-09-29 23:03 UTC
Labels: enhancement
